### PR TITLE
Implement LSTM as in paper

### PR DESCRIPTION
**Pull request by jumerckx**
My try at implementing the lstm as in the paper.

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Want to add a test? I can also add one easily enough, your choice.

**Comment by jpsamaroo** [comment]
Ok, this is looking good in general, although there are a few things I'd like to see changed (although I'm happy to merge this now, and then fix them later):
* Rename `DNCLstm` -> `DNCLSTM` and `DNCLstmCell` -> `DNCLSTMCell` (generally, one should follow capitalization of the algorithm from the source paper)
* Provide the option to specify multiple hidden layers. It seems from the paper (due to the presence of the `l` index variable) that there are multiple hidden layers within a single LSTM. The implementation I have locally has this, although I don't use `Recur` like you do here (which I should).
* Default to `Float32` parameters internally? I'm not sure if the rest of Flux does this, probably not. I figured I'd mention it just in case.
* Change the tests from `begin ... end` to a testset: `@testset "DNCLSTM" begin ... end`

**Comment by jumerckx** [comment]
AFAIK multiple layers are achieved by chaining lstm's together.
On cpu, Flux's layers are initialized with float64, only when doing |>gpu they get converter to float32. I'm only able to make changes tonight (utc+2) though.

**Comment by jpsamaroo** [comment]
No worries about Float64 -> Float32, we'll leave it as-is then. For chaining multiple layers, we can just add that later too. If you want to address the testset and renaming points (or object to them) before tomorrow US time then feel free, otherwise I'll merge. Or just merge it if you like things as they are.

**Comment by jpsamaroo** [comment]
Thanks!

**Pull request merged**
